# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = /home/babar/Documents/Robus/CAN_read_TX_2/CAN_read_TX_2
USER_LIB_PATH    =  /home/babar/src/Arduino/libraries
BOARD_TAG    = nano328
ARDUINO_LIBS += SPI mcp2515
# GPS pin Affichage


#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/arduino/Arduino.mk